name: Sync collabs with main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Sync collabs branch with main
        run: |
          git fetch origin
          git checkout collabs
          git merge origin/main --no-edit
          git push origin collabs
